# config for analysis

# most CPUs to ever use at once
max_cpus: 16

# amplicons sequenced by PacBio for wildtype homologs pool
amplicons: data/PacBio_amplicons.gb

# how to parse the amplicon
feature_parse_specs: data/feature_parse_specs.yaml

# do we get the sequencing data from the 'local' or 'SRA'?
seqdata_source: local

# list of PacBio sequencing runs linking barcodes to variants
pacbio_runs: data/PacBio_runs.csv

# list of Illumina sequencing runs of barcodes
barcode_runs: data/barcode_runs.csv

# wildtype sequence of mutagenized gene (for SARS2) -- can't remember if this is used at all?
wildtype_sequence: data/wildtype_sequence.fasta
site_number_offset: 330  # add this to sequential sites to get RBD numbering

# pdbs for mapping, analysis
pdb_6m0j: data/6m0j.pdb

# URLs from which we download binding & expression of mutants & variants from prior experiments
SARSr_lib61_mut_bind_expr_url: https://raw.githubusercontent.com/jbloomlab/SARSr-CoV_homolog_survey/master/results/final_variant_scores/wt_variant_scores.csv


# groups and orders of targets for plotting for lib61
mutated_targets_ordered:
  - AncSarbecovirus_MAP
  - BM48-31
  - BtKY72
  - AncAsia_MAP
  - AncSARS2a_MAP
  - GD-Pangolin
  - AncSARS2c_MAP
  - SARS-CoV-2_WH1
  - RaTG13
  - AncSARS1a_MAP
  - Rs7327
  - SARS-CoV-1_Urbani_HP03L
  - SARS-CoV-1_PC4-137_PC04
  - AncClade2_MAP

targets_ordered:
  - AncSarbecovirus_MAP
  - AncSarbecovirus_alt
  - AncSarbecovirus_alt1_ins117ins118
  - AncSarbecovirus_tree1
  - AncEurAf_alt
  - AncEurAf_tree1
  - BM48-31
  - BB9904
  - BtKY72
  - PRD-0038
  - PDF-2370
  - Khosta-1
  - Khosta-2
  - RhGB01
  - RhGB03
  - RhGB02_230B
  - RsYN04
  - AncAsia_MAP
  - AncAsia_alt
  - AncAsia_tree1
  - AncAsia_tree2
  - AncSARS2a_MAP
  - AncSARS2a_alt
  - AncSARS2c_MAP
  - SARS-CoV-2_WH1
  - SARS-CoV-2_Alpha
  - SARS-CoV-2_Beta
  - SARS-CoV-2_Delta
  - SARS-CoV-2_Omicron-BA1
  - SARS-CoV-2_Omicron-BA2
  - SARS-CoV-2_Omicron-BA5
  - SARS-CoV-2_Omicron-BQ11
  - SARS-CoV-2_Omicron-XBB15
  - BtSY2-RmCX02
  - BANAL-20-103
  - BANAL-20-236
  - RaTG13
  - GD-Pangolin
  - GX-Pangolin
  - RshSTT182
  - Rc-o319
  - Rc-kw8
  - Rc-os20
  - Rc-mk2
  - AncSARS1a_MAP
  - AncSARS1a_alt
  - AncSARS1a_tree1
  - AncSARS1a_tree2
  - AncSARS1c_MAP
  - AncSARS-CoV-1_MAP
  - AncSARS-CoV-1_alt
  - SARS-CoV-1_Sin852_HP03L
  - SARS-CoV-1_GZ-C_HP03L
  - SARS-CoV-1_Sino1-11_HP03L
  - SARS-CoV-1_Urbani_HP03L
  - SARS-CoV-1_HGZ8L1-A_HP03E
  - SARS-CoV-1_GD01_HP03L
  - SARS-CoV-1_PC4-127_PC04
  - SARS-CoV-1_PC4-13_PC04
  - SARS-CoV-1_PC4-137_PC04
  - SARS-CoV-1_GD03T0013_HP04
  - SARS-CoV-1_GZ0402_HP04
  - SARS-CoV-1_SZ1_PC03
  - YN2020B
  - LYRa11
  - WIV1
  - Rs7327
  - Rs4231
  - RsSHC014
  - Rs4084
  - BtSY1-RtLS01
  - AncClade2_MAP
  - AncClade2_alt
  - AncClade2_tree2
  - AncClade2_alt1_subs-only
  - AncClade2_alt2_del1-only
  - AncClade2_alt3_del2-only
  - AncClade2_alt4_dels-only
  - Rf4092
  - RmYN02
  - YN2013
  - ZC45
  - ZXC21
  - Rf1
  - JL2012
  - 273-2005
  - HeB2013
  - HuB2013
  - Rs4247
  - Longquan-140
  - HKU3-8
  - HKU3-1
  - GX2013
  - Shaanxi2011
  - 279-2005
  - As6526
  - Yunnan2011
  - Rs4237
  - Rs4081
  - Rp3


EurAf_extant:
  - BM48-31
  - BB9904
  - BtKY72
  - PRD-0038
  - PDF-2370
  - Khosta-1
  - Khosta-2
  - RhGB01
  - RhGB03
  - RhGB02_230B
    
RsYN04_extant:
  - RsYN04

SARS2_extant:
  - SARS-CoV-2_WH1
  - SARS-CoV-2_Alpha
  - SARS-CoV-2_Beta
  - SARS-CoV-2_Delta
  - SARS-CoV-2_Omicron-BA1
  - SARS-CoV-2_Omicron-BA2
  - SARS-CoV-2_Omicron-BA5
  - SARS-CoV-2_Omicron-BQ11
  - SARS-CoV-2_Omicron-XBB15
  - BtSY2-RmCX02
  - BANAL-20-103
  - BANAL-20-236
  - RaTG13
  - GD-Pangolin
  - GX-Pangolin
  - RshSTT182
  - Rc-o319
  - Rc-kw8
  - Rc-os20
  - Rc-mk2

SARS1_extant:
  - SARS-CoV-1_Sin852_HP03L
  - SARS-CoV-1_GZ-C_HP03L
  - SARS-CoV-1_Sino1-11_HP03L
  - SARS-CoV-1_Urbani_HP03L
  - SARS-CoV-1_HGZ8L1-A_HP03E
  - SARS-CoV-1_GD01_HP03L
  - SARS-CoV-1_PC4-127_PC04
  - SARS-CoV-1_PC4-13_PC04
  - SARS-CoV-1_PC4-137_PC04
  - SARS-CoV-1_GD03T0013_HP04
  - SARS-CoV-1_GZ0402_HP04
  - SARS-CoV-1_SZ1_PC03
  - YN2020B
  - LYRa11
  - WIV1
  - Rs7327
  - Rs4231
  - RsSHC014
  - Rs4084
  - BtSY1-RtLS01

Clade2_extant:
  - Rf4092
  - RmYN02
  - YN2013
  - ZC45
  - ZXC21
  - Rf1
  - JL2012
  - 273-2005
  - HeB2013
  - HuB2013
  - Rs4247
  - Longquan-140
  - HKU3-8
  - HKU3-1
  - GX2013
  - Shaanxi2011
  - 279-2005
  - As6526
  - Yunnan2011
  - Rs4237
  - Rs4081
  - Rp3

ancestors_MAP:
  - AncSarbecovirus_MAP
  - AncAsia_MAP
  - AncSARS2a_MAP
  - GD-Pangolin
  - AncSARS2c_MAP
  - AncSARS1a_MAP
  - Rs7327
  - AncSARS1c_MAP
  - AncSARS-CoV-1_MAP
  - AncClade2_MAP
  - AncClade2_alt1_subs-only
  - AncClade2_alt2_del1-only
  - AncClade2_alt3_del2-only
  - AncClade2_alt4_dels-only
  
ancestors_MAP_v_alt:
  - AncSarbecovirus_MAP
  - AncSarbecovirus_alt
  - AncSarbecovirus_alt1_ins117ins118
  - AncSarbecovirus_tree1
  - AncEurAf_alt
  - AncEurAf_tree1
  - AncAsia_MAP
  - AncAsia_alt
  - AncAsia_tree1
  - AncAsia_tree2
  - AncSARS2a_MAP
  - AncSARS2a_alt
  - AncSARS1a_MAP
  - AncSARS1a_alt
  - AncSARS1a_tree1
  - AncSARS1a_tree2
  - AncSARS-CoV-1_MAP
  - AncSARS-CoV-1_alt
  - AncClade2_MAP
  - AncClade2_alt
  - AncClade2_tree2
  - AncClade2_alt1_subs-only
  - AncClade2_alt2_del1-only
  - AncClade2_alt3_del2-only
  - AncClade2_alt4_dels-only

targets_low_bc:
  - RhGB03
  - RhGB02_230B
  - BtSY1-RtLS01
  - Rc-kw8
  - Rc-os20
  - Rc-mk2
  - BtSY2-RmCX02
  - SARS-CoV-2_Omicron-BA1
  - SARS-CoV-2_Omicron-BA2
  - SARS-CoV-2_Omicron-BA5
  - SARS-CoV-2_Omicron-BQ11
  - SARS-CoV-2_Omicron-XBB15


#indexing of mutated sites for mutated targets
mutant_indexing_file: data/mutated_target_indexing.csv  

#annotations about RBD sites
RBD_annotation_file: data/RBD_sites.csv
 
# output directories / files
summary_dir: results/summary
figs_dir: results/figures

#downloads of prior data
SARSr_lib61_mut_bind_expr: results/prior_DMS_data/SARSr-lib61_wts_ACE2binding_expression.csv

codon_variant_table_file_lib61: data/codon_variant_table_lib61.csv

counts_dir: results/counts
variant_counts_file: results/counts/variant_counts.csv

mAb_EC50_dir: results/bc_mAb_EC50/
mAb_EC50_file: results/bc_mAb_EC50/bc_mAb_EC50.csv

final_variant_scores_dir: results/final_variant_scores/
final_variant_scores_lib61_file: results/final_variant_scores/final_variant_scores_lib61.csv


# max error rate in gene / barcode CCSs retained for consensu building
max_error_rate: 0.0001

# Parameters for processing Illumina barcodes, assuming this structure:
#  [R2 binds] - [upstream] - [barcode] - [downstream] - [R1 binds]
#  This orientation is hard-wired in the barcode parser, but here it is opposite
#  Therefore, supplied the "downstream" sequence as reverse complemented upstream
# Passed to `dms_variants.illuminabarcodeparser.IlluminaBarcodeParser`:
illumina_barcode_parser_params:
  upstream: GGCCGC
  downstream: ''
  minq: 20
  upstream_mismatch: 1
  downstream_mismatch: 0
